-- =====================================================================
-- PAA v4.1 relational schema — PostgreSQL dialect
--
-- SPEC DEVIATION REVERSAL (docs/adr/0019): this restores the RFC's original
-- PostgreSQL substrate for the Docker deployment. It is the server-backed
-- sibling of schema_sqlite.sql (ADR-0001), selected by
-- ``StorageSettings.backend_relational == "postgres"``. The embedded SQLite
-- schema remains the laptop default; both must stay in lockstep.
--
-- LOCKSTEP INVARIANT: every table and column here mirrors schema_sqlite.sql
-- one-for-one. tests/storage/test_schema_parity.py parses both files and fails
-- the build if a table or column exists in one dialect and not the other. Only
-- *types* differ, and each difference is a deliberate use of a native
-- PostgreSQL type the SQLite dialect had to emulate:
--
--   * SQLite TEXT holding a uuid4      -> UUID
--   * SQLite TEXT holding JSON + a
--     ``CHECK (json_valid(...))``      -> JSONB (validity is intrinsic, so the
--                                        json_valid CHECKs are dropped)
--   * SQLite TEXT ISO-8601 timestamp   -> TIMESTAMPTZ
--   * SQLite INTEGER 0/1 boolean flag  -> SMALLINT ... CHECK (x IN (0,1))
--                                        (kept as 0/1, not BOOLEAN, so the
--                                        repositories' ``= 1`` predicates and
--                                        0/1 binds port unchanged)
--   * SQLite FTS5 trigram virtual table-> a pg_trgm GIN index on the base
--                                        table (the RFC's original design);
--                                        the virtual table has no PostgreSQL
--                                        equivalent and is intentionally absent.
--
-- Extensions: pgcrypto is not required (ids are generated application-side);
-- pg_trgm powers the entity trigram search the RFC specified.
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- =====================================================================
-- 1. SYSTEM STATE LEDGER — the append-only source of truth
-- =====================================================================

CREATE TABLE IF NOT EXISTS system_state_ledger (
    sequence_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id           UUID    NOT NULL UNIQUE,
    correlation_id     UUID    NOT NULL,
    session_id         UUID,
    causation_id       UUID,

    -- Per-correlation monotonic counter starting at 1. Replay orders by this
    -- rather than sequence_id so a lineage remains reconstructable even if the
    -- global sequence has gaps from rolled-back transactions.
    state_version      INTEGER NOT NULL,

    -- SPEC DEVIATION (docs/adr/0008): includes an attempt counter and
    -- discriminator so genuine retries are representable. See
    -- paa.ledger.events.compute_idempotency_key.
    idempotency_key    TEXT    NOT NULL,
    attempt            INTEGER NOT NULL DEFAULT 0,
    discriminator      TEXT,

    event_type         TEXT    NOT NULL,
    execution_mode     TEXT    NOT NULL DEFAULT 'STANDARD',
    agent_role         TEXT,
    allocated_worker_image TEXT NOT NULL DEFAULT 'paa/base_worker:v4.1',

    payload            JSONB   NOT NULL DEFAULT '{}'::jsonb,

    -- Tamper-evident chain. prev_hash of the first event in a correlation is
    -- 64 zeroes (GENESIS_HASH).
    prev_hash          TEXT    NOT NULL,
    event_hash         TEXT    NOT NULL,

    recorded_at        TIMESTAMPTZ NOT NULL,

    CONSTRAINT uq_ledger_idempotency UNIQUE (idempotency_key),
    CONSTRAINT uq_ledger_version     UNIQUE (correlation_id, state_version),
    CONSTRAINT ck_ledger_version_positive CHECK (state_version >= 1),
    CONSTRAINT ck_ledger_hash_len CHECK (length(event_hash) = 64 AND length(prev_hash) = 64)
);

CREATE INDEX IF NOT EXISTS idx_ledger_correlation_seq
    ON system_state_ledger(correlation_id, state_version ASC);
CREATE INDEX IF NOT EXISTS idx_ledger_recorded_at
    ON system_state_ledger(recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_ledger_event_type
    ON system_state_ledger(event_type, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_ledger_session
    ON system_state_ledger(session_id, sequence_id ASC);

-- ---------------------------------------------------------------------
-- Open-correlation projection (docs/adr/0010). One row per correlation,
-- updated in the same transaction as the append; recovery scans only the
-- rows where is_terminal = 0, which is bounded by in-flight work.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_state_correlation_head (
    correlation_id     UUID    PRIMARY KEY,
    session_id         UUID,
    latest_sequence_id BIGINT  NOT NULL,
    latest_state_version INTEGER NOT NULL,
    latest_event_type  TEXT    NOT NULL,
    latest_event_hash  TEXT    NOT NULL,
    execution_mode     TEXT    NOT NULL,
    is_terminal        SMALLINT NOT NULL DEFAULT 0,
    opened_at          TIMESTAMPTZ NOT NULL,
    updated_at         TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_head_terminal_bool CHECK (is_terminal IN (0, 1))
);

CREATE INDEX IF NOT EXISTS idx_head_open
    ON system_state_correlation_head(updated_at ASC) WHERE is_terminal = 0;

-- Snapshot checkpoints so replay of a long lineage need not start at v1.
CREATE TABLE IF NOT EXISTS system_state_snapshots (
    correlation_id     UUID    NOT NULL,
    state_version      INTEGER NOT NULL,
    projection         JSONB   NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (correlation_id, state_version)
);

-- =====================================================================
-- 2. COLD LAKE — immutable raw history
-- =====================================================================

CREATE TABLE IF NOT EXISTS cold_lake_signals (
    id             UUID PRIMARY KEY,
    received_at    TIMESTAMPTZ NOT NULL,
    channel        TEXT NOT NULL,
    external_id    TEXT,
    raw_payload    JSONB NOT NULL,
    content_hash   TEXT NOT NULL,
    -- Pointer into the content-addressed blob store for oversized payloads.
    -- On the server topology this is a MinIO/S3 object key (ADR-0019); on the
    -- laptop it is a cas:// URI. The column contract is identical.
    blob_uri       TEXT,
    sync_status    TEXT NOT NULL DEFAULT 'unprocessed',
    processed_at   TIMESTAMPTZ,
    error_detail   TEXT,
    CONSTRAINT ck_signal_status CHECK (
        sync_status IN ('unprocessed', 'processing', 'processed', 'malformed', 'quarantined')
    )
);

CREATE INDEX IF NOT EXISTS idx_cold_signals_routing
    ON cold_lake_signals(channel, received_at DESC);
CREATE INDEX IF NOT EXISTS idx_cold_signals_unprocessed
    ON cold_lake_signals(received_at ASC) WHERE sync_status = 'unprocessed';
CREATE UNIQUE INDEX IF NOT EXISTS uq_cold_signals_external
    ON cold_lake_signals(channel, external_id) WHERE external_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS cold_lake_artifacts_archive (
    id                 UUID PRIMARY KEY,
    signal_id          UUID REFERENCES cold_lake_signals(id) ON DELETE SET NULL,
    correlation_id     UUID,
    virtual_uri        TEXT NOT NULL UNIQUE,
    absolute_host_path TEXT NOT NULL,
    sha256_checksum    TEXT NOT NULL,
    size_bytes         BIGINT NOT NULL DEFAULT 0,
    compression        TEXT NOT NULL DEFAULT 'zstd',
    blob_uri           TEXT,
    payload_content    TEXT,
    archived_at        TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_artifact_checksum_len CHECK (length(sha256_checksum) = 64)
);

CREATE INDEX IF NOT EXISTS idx_artifacts_correlation
    ON cold_lake_artifacts_archive(correlation_id, archived_at DESC);
CREATE INDEX IF NOT EXISTS idx_artifacts_checksum
    ON cold_lake_artifacts_archive(sha256_checksum);

-- =====================================================================
-- 3. HOT SERVING — the cleaned operational layer
-- =====================================================================

CREATE TABLE IF NOT EXISTS hot_serving_entity_index (
    id                UUID PRIMARY KEY,
    class             TEXT NOT NULL,
    canonical_name    TEXT NOT NULL UNIQUE,
    aliases           JSONB NOT NULL DEFAULT '[]'::jsonb,
    importance_weight DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    confidence_rating DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    attributes        JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at        TIMESTAMPTZ NOT NULL,
    updated_at        TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_entity_importance CHECK (importance_weight BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_entity_confidence CHECK (confidence_rating BETWEEN 0.0 AND 1.0)
);

CREATE INDEX IF NOT EXISTS idx_hot_entity_lookup ON hot_serving_entity_index(class);
CREATE INDEX IF NOT EXISTS idx_hot_entity_updated ON hot_serving_entity_index(updated_at DESC);

-- The RFC's original trigram search. In SQLite this is an FTS5 virtual table
-- kept in sync by triggers (hot_serving_entity_fts); PostgreSQL expresses it
-- natively as a pg_trgm GIN index on the base table, so no shadow table and no
-- triggers are needed. This is the deliberate, documented dialect difference.
CREATE INDEX IF NOT EXISTS idx_hot_entity_trgm_name
    ON hot_serving_entity_index USING gin (canonical_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_hot_entity_trgm_aliases
    ON hot_serving_entity_index USING gin ((aliases::text) gin_trgm_ops);

-- ---------------------------------------------------------------------
-- Facts. The vector store holds embeddings; this table holds the truth and
-- the decay bookkeeping. Qdrant point ids reference fact ids 1:1.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS hot_serving_active_facts (
    id                 UUID PRIMARY KEY,
    entity_id          UUID NOT NULL REFERENCES hot_serving_entity_index(id) ON DELETE CASCADE,
    predicate          TEXT NOT NULL,
    object_value       TEXT NOT NULL,
    memory_domain      TEXT NOT NULL DEFAULT 'semantic',
    memory_scope       TEXT NOT NULL DEFAULT 'global',

    -- C0 in C(t) = C0 * exp(-lambda * t). Immutable after distillation;
    -- effective confidence is always derived, never stored.
    initial_confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    importance         DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    use_count          INTEGER NOT NULL DEFAULT 0,

    source_signal_id   UUID REFERENCES cold_lake_signals(id) ON DELETE SET NULL,
    provenance         JSONB NOT NULL DEFAULT '{}'::jsonb,
    embedding_status   TEXT NOT NULL DEFAULT 'pending',

    created_at         TIMESTAMPTZ NOT NULL,
    last_queried_at    TIMESTAMPTZ NOT NULL,
    superseded_by      UUID REFERENCES hot_serving_active_facts(id) ON DELETE SET NULL,

    CONSTRAINT ck_fact_conf CHECK (initial_confidence BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_fact_imp CHECK (importance BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_fact_embed CHECK (embedding_status IN ('pending', 'indexed', 'failed', 'skipped'))
);

CREATE INDEX IF NOT EXISTS idx_facts_entity_predicate
    ON hot_serving_active_facts(entity_id, predicate);
CREATE INDEX IF NOT EXISTS idx_facts_decay_sweep
    ON hot_serving_active_facts(memory_domain, last_queried_at ASC)
    WHERE superseded_by IS NULL;
CREATE INDEX IF NOT EXISTS idx_facts_pending_embedding
    ON hot_serving_active_facts(created_at ASC) WHERE embedding_status = 'pending';

-- Quarantine for mutually contradictory facts. RFC §4.2 forbids automatic
-- resolution; rows land here and wait for a human tie-break.
CREATE TABLE IF NOT EXISTS hot_serving_unresolved_buffer (
    id                UUID PRIMARY KEY,
    entity_id         UUID NOT NULL,
    predicate         TEXT NOT NULL,
    incumbent_fact    JSONB NOT NULL,
    challenger_fact   JSONB NOT NULL,
    conflict_score    DOUBLE PRECISION NOT NULL,
    correlation_id    UUID,
    detected_at       TIMESTAMPTZ NOT NULL,
    resolved_at       TIMESTAMPTZ,
    resolution        TEXT,
    CONSTRAINT ck_unresolved_resolution CHECK (
        resolution IS NULL OR resolution IN ('incumbent', 'challenger', 'both', 'neither')
    )
);

CREATE INDEX IF NOT EXISTS idx_unresolved_open
    ON hot_serving_unresolved_buffer(detected_at ASC) WHERE resolved_at IS NULL;

-- Graph edges. Mirrored into KuzuDB (laptop) or a Qdrant/graph server; this
-- table is the durable record so the graph can always be rebuilt.
CREATE TABLE IF NOT EXISTS hot_serving_relationships (
    id                 UUID PRIMARY KEY,
    from_entity_id     UUID NOT NULL REFERENCES hot_serving_entity_index(id) ON DELETE CASCADE,
    to_entity_id       UUID NOT NULL REFERENCES hot_serving_entity_index(id) ON DELETE CASCADE,
    rel_type           TEXT NOT NULL,
    weight             DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    confidence_decay   DOUBLE PRECISION NOT NULL DEFAULT 0.004,
    evidence_count     INTEGER NOT NULL DEFAULT 1,
    contradiction_score DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    source_memory_id   TEXT,
    origin_signal_id   TEXT,
    created_by_agent   TEXT NOT NULL DEFAULT 'memory_creator',
    valid_from         TIMESTAMPTZ NOT NULL,
    valid_to           TIMESTAMPTZ,
    CONSTRAINT uq_relationship UNIQUE (from_entity_id, to_entity_id, rel_type, valid_from),
    CONSTRAINT ck_rel_weight CHECK (weight BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_rel_type CHECK (rel_type IN (
        'DEPENDS_ON','PART_OF','DERIVED_FROM','INVOLVES','BLOCKS','CAUSES',
        'SUPPORTS','CONTRADICTS','REFERS_TO','TRIGGERED_BY','SIMILAR_TO','MUTATES'
    ))
);

CREATE INDEX IF NOT EXISTS idx_rel_from ON hot_serving_relationships(from_entity_id, rel_type);
CREATE INDEX IF NOT EXISTS idx_rel_to   ON hot_serving_relationships(to_entity_id, rel_type);
CREATE INDEX IF NOT EXISTS idx_rel_live ON hot_serving_relationships(weight DESC) WHERE valid_to IS NULL;

-- ---------------------------------------------------------------------
-- Task workspaces, sessions, skills
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS hot_serving_sessions (
    session_id     UUID PRIMARY KEY,
    session_name   TEXT NOT NULL,
    status         TEXT NOT NULL DEFAULT 'QUEUED',
    permission_mode TEXT NOT NULL DEFAULT 'ASK',
    workspace_path TEXT,
    metadata       JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at     TIMESTAMPTZ NOT NULL,
    updated_at     TIMESTAMPTZ NOT NULL,
    closed_at      TIMESTAMPTZ,
    CONSTRAINT ck_session_status CHECK (
        status IN ('QUEUED','IN_PROGRESS','PAUSED','COMPLETED','FAILED','ABANDONED')
    )
);

CREATE INDEX IF NOT EXISTS idx_sessions_active
    ON hot_serving_sessions(updated_at DESC) WHERE closed_at IS NULL;

CREATE TABLE IF NOT EXISTS hot_serving_task_workspaces_vault (
    id                UUID PRIMARY KEY,
    task_id           UUID NOT NULL REFERENCES hot_serving_entity_index(id) ON DELETE CASCADE,
    filename          TEXT NOT NULL,
    file_content      TEXT NOT NULL DEFAULT '',
    checksum          TEXT NOT NULL,
    last_mutation_by  TEXT NOT NULL,
    revision          INTEGER NOT NULL DEFAULT 1,
    synchronized_at   TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_task_file_mapping UNIQUE (task_id, filename),
    CONSTRAINT ck_vault_mutator CHECK (
        last_mutation_by IN ('HUMAN_USER','SYSTEM_KERNEL','WORKER_CELL','MEMORY_CURATOR')
    )
);

CREATE TABLE IF NOT EXISTS hot_serving_skill_registry (
    id                   UUID PRIMARY KEY,
    skill_name           TEXT NOT NULL UNIQUE,
    provider             TEXT NOT NULL DEFAULT 'claw_hub',
    version              TEXT NOT NULL DEFAULT '0.1.0',
    description          TEXT NOT NULL,
    input_schema         JSONB NOT NULL,
    output_schema        JSONB NOT NULL,
    risk_profile         DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    required_permissions JSONB NOT NULL DEFAULT '[]'::jsonb,
    reliability_weight   DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    invocation           JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_uri           TEXT,
    source_checksum      TEXT,
    signature            TEXT,
    is_active            SMALLINT NOT NULL DEFAULT 1,
    installed_at         TIMESTAMPTZ NOT NULL,
    updated_at           TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_skill_risk CHECK (risk_profile BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_skill_reliability CHECK (reliability_weight BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_skill_provider CHECK (provider IN ('claw_hub','mcp_server','native','marketplace')),
    CONSTRAINT ck_skill_active_bool CHECK (is_active IN (0,1))
);

CREATE INDEX IF NOT EXISTS idx_skills_active
    ON hot_serving_skill_registry(skill_name) WHERE is_active = 1;

CREATE TABLE IF NOT EXISTS hot_serving_agent_registry (
    id                UUID PRIMARY KEY,
    agent_name        TEXT NOT NULL UNIQUE,
    role              TEXT NOT NULL,
    description       TEXT NOT NULL DEFAULT '',
    allowed_tools     JSONB NOT NULL DEFAULT '[]'::jsonb,
    granted_permissions JSONB NOT NULL DEFAULT '[]'::jsonb,
    recursion_ceiling INTEGER NOT NULL DEFAULT 0,
    max_retries       INTEGER NOT NULL DEFAULT 1,
    token_ceiling     INTEGER NOT NULL DEFAULT 2048,
    model_preference  TEXT,
    is_active         SMALLINT NOT NULL DEFAULT 1,
    created_at        TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_agent_active_bool CHECK (is_active IN (0,1))
);

-- ---------------------------------------------------------------------
-- Telemetry, evaluation, recovery bookkeeping
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS hot_serving_execution_runs (
    trace_id          UUID PRIMARY KEY,
    correlation_id    UUID NOT NULL,
    session_id        UUID,
    span_parent_id    UUID,
    agent_role        TEXT NOT NULL,
    skill_name        TEXT,
    modality          TEXT NOT NULL,
    permission_mode   TEXT NOT NULL,
    started_at        TIMESTAMPTZ NOT NULL,
    ended_at          TIMESTAMPTZ,
    duration_ms       BIGINT,
    exit_code         INTEGER,
    tokens_consumed   INTEGER NOT NULL DEFAULT 0,
    peak_rss_mb       DOUBLE PRECISION,
    model_used        TEXT,
    escalated         SMALLINT NOT NULL DEFAULT 0,
    telemetry         JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_detail      TEXT,
    CONSTRAINT ck_run_escalated_bool CHECK (escalated IN (0,1))
);

CREATE INDEX IF NOT EXISTS idx_runs_correlation ON hot_serving_execution_runs(correlation_id, started_at ASC);
CREATE INDEX IF NOT EXISTS idx_runs_skill ON hot_serving_execution_runs(skill_name, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_runs_started ON hot_serving_execution_runs(started_at DESC);

CREATE TABLE IF NOT EXISTS hot_serving_evaluation_results (
    id             UUID PRIMARY KEY,
    correlation_id UUID NOT NULL,
    evaluator      TEXT NOT NULL,
    verdict        TEXT NOT NULL,
    score          DOUBLE PRECISION,
    findings       JSONB NOT NULL DEFAULT '[]'::jsonb,
    evaluated_at   TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_eval_verdict CHECK (verdict IN ('PASS','FAIL_REJECT_RETRY','FAIL_ESCALATE','SKIPPED'))
);

CREATE INDEX IF NOT EXISTS idx_eval_correlation ON hot_serving_evaluation_results(correlation_id);

-- Filesystem checkpoints used to detect and undo post-crash drift.
CREATE TABLE IF NOT EXISTS hot_serving_recovery_marks (
    id             UUID PRIMARY KEY,
    correlation_id UUID NOT NULL,
    state_version  INTEGER NOT NULL,
    workspace_path TEXT NOT NULL,
    manifest       JSONB NOT NULL,
    manifest_hash  TEXT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_recovery_mark UNIQUE (correlation_id, state_version)
);

CREATE INDEX IF NOT EXISTS idx_marks_correlation
    ON hot_serving_recovery_marks(correlation_id, state_version DESC);

-- Registry describing each logical memory domain's policy (RFC §4.1).
CREATE TABLE IF NOT EXISTS hot_serving_memory_registry (
    domain           TEXT PRIMARY KEY,
    storage_engine   TEXT NOT NULL,
    decay_lambda     DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    prune_floor      DOUBLE PRECISION NOT NULL DEFAULT 0.15,
    retrieval_protocol TEXT NOT NULL,
    is_immutable     SMALLINT NOT NULL DEFAULT 0,
    description      TEXT NOT NULL DEFAULT '',
    CONSTRAINT ck_memreg_immutable_bool CHECK (is_immutable IN (0,1))
);

CREATE TABLE IF NOT EXISTS hot_serving_policy_rules (
    id           UUID PRIMARY KEY,
    rule_name    TEXT NOT NULL UNIQUE,
    rule_kind    TEXT NOT NULL,
    pattern      TEXT NOT NULL,
    severity     TEXT NOT NULL DEFAULT 'block',
    threshold    DOUBLE PRECISION,
    source_file  TEXT,
    is_active    SMALLINT NOT NULL DEFAULT 1,
    created_at   TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_policy_kind CHECK (rule_kind IN ('regex','ast','anti_goal_vector','permission','path_guard')),
    CONSTRAINT ck_policy_severity CHECK (severity IN ('block','gate','warn')),
    CONSTRAINT ck_policy_active_bool CHECK (is_active IN (0,1))
);

-- =====================================================================
-- 4. DURABLE QUEUE
--
-- On the server topology the live dispatch fabric is Redis (ADR-0005 /
-- ADR-0019, ``backend_queue == "redis"``). These tables remain defined so that
-- the SQLite-compatible durable queue can also run against PostgreSQL, and so
-- the schemas stay column-for-column identical across dialects.
-- =====================================================================

CREATE TABLE IF NOT EXISTS queue_messages (
    id              UUID PRIMARY KEY,
    stream          TEXT NOT NULL,
    correlation_id  UUID,
    session_id      UUID,
    priority        INTEGER NOT NULL DEFAULT 100,
    payload         JSONB NOT NULL,
    status          TEXT NOT NULL DEFAULT 'ready',
    attempts        INTEGER NOT NULL DEFAULT 0,
    max_attempts    INTEGER NOT NULL DEFAULT 3,
    claimed_by      TEXT,
    claimed_at      TIMESTAMPTZ,
    visible_after   TIMESTAMPTZ NOT NULL,
    enqueued_at     TIMESTAMPTZ NOT NULL,
    completed_at    TIMESTAMPTZ,
    last_error      TEXT,
    CONSTRAINT ck_queue_status CHECK (status IN ('ready','claimed','done','dead'))
);

CREATE INDEX IF NOT EXISTS idx_queue_dispatch
    ON queue_messages(stream, priority ASC, visible_after ASC, enqueued_at ASC)
    WHERE status = 'ready';
CREATE INDEX IF NOT EXISTS idx_queue_reclaim
    ON queue_messages(visible_after ASC) WHERE status = 'claimed';
CREATE INDEX IF NOT EXISTS idx_queue_dead
    ON queue_messages(stream, enqueued_at DESC) WHERE status = 'dead';

CREATE TABLE IF NOT EXISTS queue_locks (
    lock_key    TEXT PRIMARY KEY,
    holder      TEXT NOT NULL,
    acquired_at TIMESTAMPTZ NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_locks_expiry ON queue_locks(expires_at ASC);

-- =====================================================================
-- 5. MARKETPLACE
-- =====================================================================

CREATE TABLE IF NOT EXISTS marketplace_packages (
    id              UUID PRIMARY KEY,
    package_name    TEXT NOT NULL,
    version         TEXT NOT NULL,
    kind            TEXT NOT NULL,
    publisher       TEXT NOT NULL,
    publisher_key   TEXT,
    description     TEXT NOT NULL DEFAULT '',
    manifest        JSONB NOT NULL,
    content_hash    TEXT NOT NULL,
    signature       TEXT,
    signature_state TEXT NOT NULL DEFAULT 'unverified',
    source_registry TEXT,
    installed_at    TIMESTAMPTZ,
    trust_score     DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    CONSTRAINT uq_marketplace_pkg UNIQUE (package_name, version),
    CONSTRAINT ck_market_kind CHECK (kind IN ('skill','agent','playbook','config','bundle')),
    CONSTRAINT ck_market_sig CHECK (signature_state IN ('unverified','valid','invalid','untrusted_key'))
);

CREATE INDEX IF NOT EXISTS idx_marketplace_installed
    ON marketplace_packages(installed_at DESC) WHERE installed_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS marketplace_trusted_keys (
    key_id      TEXT PRIMARY KEY,
    public_key  TEXT NOT NULL,
    owner       TEXT NOT NULL,
    added_at    TIMESTAMPTZ NOT NULL,
    revoked_at  TIMESTAMPTZ
);

-- =====================================================================
-- 6. SELF-IMPROVEMENT
-- =====================================================================

CREATE TABLE IF NOT EXISTS improvement_reflections (
    id              UUID PRIMARY KEY,
    window_start    TIMESTAMPTZ NOT NULL,
    window_end      TIMESTAMPTZ NOT NULL,
    task_domain     TEXT NOT NULL,
    friction_score  DOUBLE PRECISION NOT NULL,
    corrections     INTEGER NOT NULL DEFAULT 0,
    rollbacks       INTEGER NOT NULL DEFAULT 0,
    successes       INTEGER NOT NULL DEFAULT 0,
    extracted_rule  TEXT,
    applied_to      TEXT,
    created_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reflections_domain
    ON improvement_reflections(task_domain, created_at DESC);

CREATE TABLE IF NOT EXISTS improvement_skill_weights (
    skill_name      TEXT PRIMARY KEY,
    reliability     DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    sample_count    INTEGER NOT NULL DEFAULT 0,
    mean_latency_s  DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    correction_rate DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    updated_at      TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_weight_reliability CHECK (reliability BETWEEN 0.0 AND 1.0)
);

-- =====================================================================
-- 7. SCHEMA VERSION
-- =====================================================================

CREATE TABLE IF NOT EXISTS schema_migrations (
    version     INTEGER PRIMARY KEY,
    applied_at  TIMESTAMPTZ NOT NULL,
    description TEXT NOT NULL
);
